[build]
  base = "interview-helper-frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true" # ðŸš€ tells Netlify to skip Next.js detection

[[plugins]]
  package = "@netlify/plugin-inline-functions-env"